### ISSUE TITLE
undefined method `fuzzily_searchable' on Rails 7

### ISSUE THREAD

**Issue by ragesoss** [2called-chaos/fuzzily#1]
I'm working on moving from Rails 6.1 to Rails 7, and I've found that on Rails 7, models that are instrumented with `fuzzily_searchable` throw errors like this:

```
NoMethodError:
       undefined method `fuzzily_searchable' for Faq:Class
```
