### PR TITLE
Add support for Rails 7+

### LINKED ISSUE #1: undefined method `fuzzily_searchable' on Rails 7
I'm working on moving from Rails 6.1 to Rails 7, and I've found that on Rails 7, models that are instrumented with `fuzzily_searchable` throw errors like this:

```
NoMethodError:
       undefined method `fuzzily_searchable' for Faq:Class
```

### PR DESCRIPTION
**Pull request by ragesoss**
The `searchable` module broke on Rails 7 because it was explicitly looking for Rails 5 or 6. The behavior was actually the same between 5 and 6, and works the same way on Rails 7, so I've simplified the logic for which class methods to include: all of them. Rails versions older than 5.1 are already incompatible with the gemspec, so this change should keep the gem working through major version changes in the future.

Resolves #1

### CODE REVIEW

**Comment by 2called-chaos** [comment]
Thank you!

**Comment by ragesoss** [comment]
@2called-chaos thanks for doing the release! This was the last blocker for getting my app onto Rails 7. :-)

**Comment by 2called-chaos** [comment]
You're welcome. May I ask if you happen to be familiar with GitHub actions? I tried to get the tests working again (uses old travis) but I have no clue what the issue is here https://github.com/2called-chaos/fuzzily/actions/runs/2755158334/workflow

**Comment by ragesoss** [comment]
Hmm... what a cryptic error message! I don't spot anything wrong with the config. It seems really weird that it would error on line 1.

**Comment by ragesoss** [comment]
Maybe the first `step` (the checkout action) needs a `name`?

**Comment by 2called-chaos** [comment]
The Ruby template that GitHub suggests has it the same way without a name. I can also run it locally with `act`. I think this is a git error message. Maybe because this is a fork. I will ask in the community forums I guess. Thanks for taking a look!
